var catalogPages = [
  {
    "id":"10151",
    "type":"CatalogPage",
    "masterCatalogPageNumber":1,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10151"
    }
  },
  {
    "id":"10155",
    "type":"CatalogPage",
    "masterCatalogPageNumber":2,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10155"
    }
  },
  {
    "id":"10157",
    "type":"CatalogPage",
    "masterCatalogPageNumber":3,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10157"
    }
  },
  {
    "id":"10450",
    "type":"CatalogPage",
    "masterCatalogPageNumber":4,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10450"
    }
  },
  {
    "id":"10460",
    "type":"CatalogPage",
    "masterCatalogPageNumber":5,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10460"
    }
  },
  {
    "id":"10470",
    "type":"CatalogPage",
    "masterCatalogPageNumber":6,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10470"
    }
  },
  {
    "id":"10480",
    "type":"CatalogPage",
    "masterCatalogPageNumber":7,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10480"
    }
  },
  {
    "id":"10870",
    "type":"CatalogPage",
    "masterCatalogPageNumber":8,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10870"
    }
  },
  {
    "id":"10880",
    "type":"CatalogPage",
    "masterCatalogPageNumber":9,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10880"
    }
  },
  {
    "id":"10490",
    "type":"CatalogPage",
    "masterCatalogPageNumber":10,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10490"
    }
  },
  {
    "id":"10500",
    "type":"CatalogPage",
    "masterCatalogPageNumber":11,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10500"
    }
  },
  {
    "id":"10150",
    "type":"CatalogPage",
    "masterCatalogPageNumber":14,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10150"
    }
  },
  {
    "id":"10160",
    "type":"CatalogPage",
    "masterCatalogPageNumber":15,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10160"
    }
  },
  {
    "id":"10530",
    "type":"CatalogPage",
    "masterCatalogPageNumber":16,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10530"
    }
  },
  {
    "id":"10540",
    "type":"CatalogPage",
    "masterCatalogPageNumber":17,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10540"
    }
  },
  {
    "id":"10170",
    "type":"CatalogPage",
    "masterCatalogPageNumber":18,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10170"
    }
  },
  {
    "id":"10180",
    "type":"CatalogPage",
    "masterCatalogPageNumber":19,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10180"
    }
  },
  {
    "id":"10190",
    "type":"CatalogPage",
    "masterCatalogPageNumber":20,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10190"
    }
  },
  {
    "id":"10200",
    "type":"CatalogPage",
    "masterCatalogPageNumber":21,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10200"
    }
  },
  {
    "id":"10550",
    "type":"CatalogPage",
    "masterCatalogPageNumber":22,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10550"
    }
  },
  {
    "id":"10560",
    "type":"CatalogPage",
    "masterCatalogPageNumber":23,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10560"
    }
  },
  {
    "id":"10203",
    "type":"CatalogPage",
    "masterCatalogPageNumber":24,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10203"
    }
  },
  {
    "id":"10205",
    "type":"CatalogPage",
    "masterCatalogPageNumber":25,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10205"
    }
  },
  {
    "id":"10207",
    "type":"CatalogPage",
    "masterCatalogPageNumber":26,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10207"
    }
  },
  {
    "id":"10206",
    "type":"CatalogPage",
    "masterCatalogPageNumber":26,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10206"
    }
  },
  {
    "id":"10570",
    "type":"CatalogPage",
    "masterCatalogPageNumber":27,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10570"
    }
  },
  {
    "id":"10580",
    "type":"CatalogPage",
    "masterCatalogPageNumber":28,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10580"
    }
  },
  {
    "id":"10210",
    "type":"CatalogPage",
    "masterCatalogPageNumber":29,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10210"
    }
  },
  {
    "id":"10220",
    "type":"CatalogPage",
    "masterCatalogPageNumber":30,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10220"
    }
  },
  {
    "id":"10590",
    "type":"CatalogPage",
    "masterCatalogPageNumber":31,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10590"
    }
  },
  {
    "id":"10600",
    "type":"CatalogPage",
    "masterCatalogPageNumber":32,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10600"
    }
  },
  {
    "id":"10230",
    "type":"CatalogPage",
    "masterCatalogPageNumber":33,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10230"
    }
  },
  {
    "id":"10240",
    "type":"CatalogPage",
    "masterCatalogPageNumber":34,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10240"
    }
  },
  {
    "id":"10610",
    "type":"CatalogPage",
    "masterCatalogPageNumber":35,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10610"
    }
  },
  {
    "id":"10620",
    "type":"CatalogPage",
    "masterCatalogPageNumber":36,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10620"
    }
  },
  {
    "id":"10250",
    "type":"CatalogPage",
    "masterCatalogPageNumber":37,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10250"
    }
  },
  {
    "id":"10260",
    "type":"CatalogPage",
    "masterCatalogPageNumber":38,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10260"
    }
  },
  {
    "id":"10630",
    "type":"CatalogPage",
    "masterCatalogPageNumber":39,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10630"
    }
  },
  {
    "id":"10640",
    "type":"CatalogPage",
    "masterCatalogPageNumber":40,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10640"
    }
  },
  {
    "id":"10270",
    "type":"CatalogPage",
    "masterCatalogPageNumber":41,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10270"
    }
  },
  {
    "id":"10280",
    "type":"CatalogPage",
    "masterCatalogPageNumber":42,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10280"
    }
  },
  {
    "id":"10290",
    "type":"CatalogPage",
    "masterCatalogPageNumber":43,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10290"
    }
  },
  {
    "id":"10300",
    "type":"CatalogPage",
    "masterCatalogPageNumber":44,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10300"
    }
  },
  {
    "id":"10310",
    "type":"CatalogPage",
    "masterCatalogPageNumber":45,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10310"
    }
  },
  {
    "id":"10320",
    "type":"CatalogPage",
    "masterCatalogPageNumber":46,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10320"
    }
  },
  {
    "id":"10330",
    "type":"CatalogPage",
    "masterCatalogPageNumber":47,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10330"
    }
  },
  {
    "id":"10340",
    "type":"CatalogPage",
    "masterCatalogPageNumber":48,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10340"
    }
  },
  {
    "id":"10341",
    "type":"CatalogPage",
    "masterCatalogPageNumber":49,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10341"
    }
  },
  {
    "id":"10342",
    "type":"CatalogPage",
    "masterCatalogPageNumber":50,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10342"
    }
  },
  {
    "id":"10650",
    "type":"CatalogPage",
    "masterCatalogPageNumber":51,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10650"
    }
  },
  {
    "id":"10660",
    "type":"CatalogPage",
    "masterCatalogPageNumber":52,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10660"
    }
  },
  {
    "id":"10350",
    "type":"CatalogPage",
    "masterCatalogPageNumber":53,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10350"
    }
  },
  {
    "id":"10360",
    "type":"CatalogPage",
    "masterCatalogPageNumber":54,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10360"
    }
  },
  {
    "id":"10370",
    "type":"CatalogPage",
    "masterCatalogPageNumber":55,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10370"
    }
  },
  {
    "id":"10380",
    "type":"CatalogPage",
    "masterCatalogPageNumber":56,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10380"
    }
  },
  {
    "id":"10390",
    "type":"CatalogPage",
    "masterCatalogPageNumber":57,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10390"
    }
  },
  {
    "id":"10400",
    "type":"CatalogPage",
    "masterCatalogPageNumber":58,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10400"
    }
  },
  {
    "id":"10410",
    "type":"CatalogPage",
    "masterCatalogPageNumber":59,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10410"
    }
  },
  {
    "id":"10420",
    "type":"CatalogPage",
    "masterCatalogPageNumber":60,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10420"
    }
  },
  {
    "id":"10670",
    "type":"CatalogPage",
    "masterCatalogPageNumber":61,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10670"
    }
  },
  {
    "id":"10680",
    "type":"CatalogPage",
    "masterCatalogPageNumber":62,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10680"
    }
  },
  {
    "id":"10690",
    "type":"CatalogPage",
    "masterCatalogPageNumber":63,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10690"
    }
  },
  {
    "id":"10700",
    "type":"CatalogPage",
    "masterCatalogPageNumber":64,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10700"
    }
  },
  {
    "id":"10710",
    "type":"CatalogPage",
    "masterCatalogPageNumber":65,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10710"
    }
  },
  {
    "id":"10720",
    "type":"CatalogPage",
    "masterCatalogPageNumber":66,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10720"
    }
  },
  {
    "id":"10730",
    "type":"CatalogPage",
    "masterCatalogPageNumber":67,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10730"
    }
  },
  {
    "id":"10740",
    "type":"CatalogPage",
    "masterCatalogPageNumber":68,
    "links":{
      "self":"https://sb.conductiv.com/capi/rest/v2/VANSSB/master-catalogs/10070/pages/10740"
    }
  }
];

var page = require('webpage').create();
page.viewportSize = {
	width : 768,
	height : 1024
};
var url = 'http://192.168.10.151:9000/headless-login.html?username=admin1&password=conductiv12&tenant=VANSSB&path=catalog%2Fmaster%2F10070%2Fpage%2F';
var renderPage = function(index) {
	if (index >= catalogPages.length) {
		return;
	}
	console.log("setting up capture for" + index);
	var pageNumber = catalogPages[index].masterCatalogPageNumber;
	var pageId = catalogPages[index].id;

	var isRedirected = false;
	page.open(url + pageId, function() {
		if (isRedirected) {
			console.log('capturing page' + pageNumber + '.png');

			setTimeout(function() {
				page.render('page' + pageNumber + '.png')
			}, 2000);
		} else {
			isRedirected = true;
		}

	});
	setTimeout(function() {
		var nextPage = index + 1;
		console.log("going to next page");
		renderPage(nextPage);
	}, 5000);
};
renderPage(0);

